### ISSUE TITLE
bernard and crypted drive

### ISSUE THREAD

**Issue by xfouloux** [Cloudbox/autoscan#104]
Hi,

is bernard able to use an rclone encrypted drive ?

not seeing anything in the https://github.com/m-rots/bernard repo about this

Can you confirm ?

Thanks

**Comment by m-rots** [comment]
Bernard does not support encrypted Shared Drives. Furthermore, Bernard does not support My Drive in its entirety.

**Comment by beyondmeat** [comment]
@m-rots that's unfortunate. Is there any plans to support rclone's crypt in bernard?

This needs to be a disclaimer in the readme/docs. I had to find this issue to figure out why it wasn't working.

**Comment by m-rots** [comment]
> @m-rots that's unfortunate. Is there any plans to support rclone's crypt in bernard?
> 
> This needs to be a disclaimer in the readme/docs. I had to find this issue to figure out why it wasn't working.

The current version of Bernard is likely to be replaced by A-Train. A-Train includes this disclaimer in its readme, so that should make it clear that there is no support for RClone encryption.

Regarding plans to support RClone's encryption. The simple answer is no. The last time I checked RClone used some non-standard encryption algorithms which I would need to write from scratch, something I will not do. If they switched to some industry standard encryption method, then it would not be much work to add support for it.

**Comment by peterbaumert** [comment]
Why dont you just use `rclone backend decode` for example?
This feature would be very useful :)

**Comment by m-rots** [comment]
> Why dont you just use `rclone backend decode` for example?
> This feature would be very useful :)

Will look into it

**Comment by hekmon** [comment]
I think it is possible to acheive a middleground:

Take the following remote encrypted path from a remote encrypted rclone team drive:
`/obfus1/obfus2/obfus3/obfus4`
which should translate to
`/movies/radarr/MovieTitleFolder/MovieTitle`

- `obfus1` and `obfus2` are static path parts, they do not change (and the plex library is most likely based on them, once deoffuscated)
- `obfus3` and `obfus4` are  dynamic and will change at each detection

A first part of the solution is the following:
- Thanks to the autoscan rewrite rules on the bernard backend, `obfus1` and `obfus2` could be rewritten to the correct path (its easy to find out which is which with rclone crypt backend `show_mapping` option).
- This would allow autoscan to determine the correct library

It actually already works, I tested it: the correct library is detected from the autoscan log based on the partially unofuscated path (`/movies/radarr/obfus3/obfus4`).

The final part of the problem is:
- autoscan uses the library [partial scan](https://support.plex.tv/articles/201638786-plex-media-server-url-commands/) to perfectly target the new files and therefor start a very efficient scan, but as the last part of the path is not deobfuscated, the targeted scan fails and the new file is not detected
- the last part of the path, the dynamic one, can not be pre determined and therefor not put in the rewriting rules: it can not and should not be used during the scan process

So here is how encrypted library could be supported:
- With a given (new) option, we could tell autoscan in the bernad config file that the backend is encrypted
- If this option is enabled on this backend, instead of triggering a partial scan, autoscan could start a full (single) library scan using the base path rewritten to determine which library to rescan

It is not a specific targetted scan as autoscan is normally capable of but it still enable support of encrypted team drive while avoiding to start a complete libraries scan (only a single library is rescanned entirely).

Call it a compromise :)
