### ISSUE TITLE
Anchor file is unavailable

### ISSUE THREAD

**Issue by hwwilliams** [Cloudbox/autoscan#114]
Hi,

I'm not sure what I'm doing wrong but I'm getting errors about an anchor file being unavailable even though as its displaying the error I can login to the docker container and ls the file. It happens constantly even with the network share and docker volume are mounted.

I have two anchor files specified as follows:

```yaml
anchors::
  - /data/movies/autoscan-movies-anchor
  - /data/tv/autoscan-tv-anchor
```

They are empty files, the tv anchor never has issues.

![image](https://user-images.githubusercontent.com/20447447/115580432-11f49300-a295-11eb-8efd-338ddd7cc666.png)

**Comment by m-rots** [comment]
Could maybe be a permission issue then?

**Comment by hwwilliams** [comment]
Perhaps, though I had created both of them the same way. After stopping the container, recreating the files, and then starting it back up again the error is gone now. Not sure what the difference was honestly.

**Comment by enz1ey** [comment]
I know this has been closed for some time, but I am still seeing this issue. There's no rhyme or reason, and it happens on multiple hosts for me. I can restart the container and autoscan works just fine for a while, but eventually I will notice in Plex a lot of episodes/movies showing "unavailable" and I know to check the autoscan container logs because it's not scanning replaced files anymore. Sure enough, there will be a few days' worth of "anchor file unavailable" errors, even though the file is definitely available, can be listed inside the container console as well as in a terminal on the host. Restarting the container will resolve the issue, but it will happen again soon after.

Unfortunately, I have had to stop using anchor files and write my own cron script to re-mount my media if/when necessary. I have this script output any actions to a log, and in over a month it hasn't had to re-mount anything yet, so I'm not sure why autoscan says the anchor files aren't available. It's not a permission issue because it does work, it just inexplicably stops after a while.

**Comment by himea-saito** [comment]
This is super necro but stumbled across this issue when Googling the same issue. Turns out I accidentally made the local.anchor a folder/directory instead of an empty text file. Hope that helps anyone else stuck in a spiral of madness like I was. Also double check the filepath has read permissions to all groups, that was the initial cause of my error.

**Comment by eihns** [comment]
same for me... using mergefs with dropbox and local
