### ISSUE TITLE
Scan based on file creation date/time

### ISSUE THREAD

**Issue by ajhorvath20** [Cloudbox/autoscan#127]
Hi, 

I have no clue if its possible or not. I run manual trigger most of the time and that means I can only scan one TV Show or Movie at a time. But would be great if I can select the date from calendar which will trigger the scan based on last number of days. This way I have lot of files scanned but not the whole library.  

I hope this explains little bit. 

Thanks

**Comment by l3uddz** [comment]
This would best be achieved using an external script hooked up to cron.

Script could perform the following:

1. Find all files modified since 2021-07-14 00:00:00
2. Send files to autoscan manual

Hook this up to cron on an interval you are comfortable with.

It is unlikely this will ever be added directly to autoscan.

**Comment by ajhorvath20** [comment]
Horoay you are very clever :) thank you so much.

I am using Web UI for manual scan but I will use it find and then scan. 

Thanks again.
