### ISSUE TITLE
latest plex version 1.32.7 breaks autoscan

### ISSUE THREAD

**Issue by JohnFawkes** [Cloudbox/autoscan#218]
error="scan: 404 Not Found: target unavailable"

Logs are getting spammed with this and as soon as I downgraded to 1.32.6 autoscan started working again. I think something changed in the api that calls the scanning

**Comment by rg9400** [comment]
PUT/POST requests throw a 404. https://forums.plex.tv/t/refresh-endpoint-put-post-requests-started-throwing-404s-in-version-1-32-7-7484/853588

It is unclear if this is intentional or not since Plex apparently uses 404 as Method Not Allowed. However, GET still works with the same setup, so a very simple fix is just to switch the request method in case Plex is not looking to roll it back.

**Comment by m-rots** [comment]
There's a fix available in `cloudb0x/autoscan:plex-hotfix`. Looking to merge asap!

**Comment by JohnFawkes** [comment]
> There's a fix available in `cloudb0x/autoscan:plex-hotfix`. Looking to merge asap!

Awesome! Thanks so much!

**Comment by m-rots** [comment]
The fix is now live in `cloudb0x/autoscan:latest`. In the rare event that Plex decides to rollback the changes, the change of the HTTP method should generally be non-destructive and is tested to be backwards-compatible. Of course, it's also an option that Plex decides to change the method to `PUT` or `POST`, which are more aligned to the HTTP spec. In this case, we'll follow-up #219 to make an exception for version 1.32.7.7484 to use `GET`.

**Comment by JohnFawkes** [comment]
Awesome! Thanks so much @m-rots and everyone else involved!

**Comment by alneven** [comment]
I have only installed autoscan the first time today, started direct with the v1.6.1 docker
and it is working for me now, manual from bazarr and the radarr trigger as well

thanks!
