### ISSUE TITLE
Plex does not "scan the whole library" when a file is added, so what is the benefit of autoscan

### ISSUE THREAD

**Issue by stevezau** [Cloudbox/autoscan#227]
Hello! I came across this project. I am always looking for ways to improve my setup. 

Reading the docs, I am confused as it seems to suggest this app provides a better approach to adding files to Plex due to how Plex scans the entire library. But, when Sonarr or Radarr imports a file to my plex server, it only scans the folder that changed, not the entire library. 

So, I am trying to understand what I am missing here and what benefits autoscan provides if your files etc are all on the same server/local? 

Thanks!

**Comment by stevezau** [comment]
Any guidance here?

**Comment by UnknownWitcher** [comment]
Good luck getting a developer to answer. Here is my take on autoscan.

Autoscan tells plex to run a partial scan, which is the same function plex has built in, except autoscan includes extra features that plex doesn't have.

**Delay scans.** - Autoscan will continue to delay the scan each time the same path is given.

This can reduce the amount of times plex has to run a partial scan, for example lets say sonarr is processing 100 episodes between 4 seasons, a partial scan in plex could result in 100 seperate scans being sent, however, by delaying the scan plex could potentially only receive 4 scan requests.

**Works with network storage.**

Plex can't detect changes on network storage, so if you use NAS or rclone + cloud provider, then you'll have to scan periodically. However, wih autoscan we use triggers which allow us to work around this issue.

- A-Train detects changes on google storage
- Inotify detects changes on your file system (you would use this if you want it to act similarly to plex partial scan)
- arrs can tell autoscan when a file has been added to your library path.
- manual is handy if you want to scan a path manually.

**Anchors help prevent scanning when a storage path is not available**

If you're using a google, dropbox or your own NAS and you're mounting this to your media server by rclone, SMB etc.. or even if you were using USB external HDDs, if for some reason that storage goes offline and plex performs a scan, it will remove all of your media, this also applies to emby and jellyfin.

However, if we setup anchors, then autoscan will not tell our media server to scan if our storage is offline.

### There are a few things I'm probably forgetting but overall autoscan is more useful for some of us, however there is downside.

Autoscan will fail if it doesn't detect your media server, so if autoscan loads before your media server loads, it will crash, if your media server needs restarted or you need to take it down for a minute, autoscan might crash. This (sadly) is by design, it gives you the ability to control the scan of multiple media servers (plex, jellyfin, emby) and instead of having a solution to purge the database for each server that is inactive for lets say 24 hours, they'd rather have autoscan fail.

If autoscan fails, even if your media server is running, it wont scan the new files, if you use the starr apps to trigger this then it forces you to manually scan everything that is missing, which is a pain as I've had to do it.

A workaround (that I have yet to try) would be to avoid adding autoscan to the ARRs and instead add a script that sends the scan paths directly to the autoscan database, so even if it crashes the information is there for autoscan to do its job.

**Comment by stevezau** [comment]
I am using local storage so it looks like this project won't benefit me much. Thanks for the info
