### ISSUE TITLE
graceful timeout for missing target on startup

### ISSUE THREAD

**Issue by Iguana9999phil** [Cloudbox/autoscan#36]
Autoscan looks good, testing it now and noticed that when a target is not available it will restart the autoscan process until it's available. This is giving issues with autoscan not working when multiple targets are configured and one of those is down (for whatever reason)

An x retry and then ignore the missing target would be ideal.

**Comment by m-rots** [comment]
This design decision was intentional as all targets should be up at all times. If a target is offline because of a crash or a periodic backup, then we do not want to simply skip the target as it will become out-of-sync with the other targets. In case of Plex, you'd have to do a full manual scan in case it would become out-of-sync, something we really want to avoid.

If you manually shut down a target because of whatever reason, then you should remove the target from Autoscan's config.

**Comment by Iguana9999phil** [comment]
Ok, but what if autoscan is already running and the target goes offline?

**Comment by m-rots** [comment]
If the target goes offline, then Autoscan (in its current state) will wait for the target to become available. Once it is, it will resume operation.

**Comment by Iguana9999phil** [comment]
And that means the whole process is on hold or only the trigger for that target?

**Comment by m-rots** [comment]
All triggers will continue to receive events. However, the scans will not be forwarded to the targets until all targets are available.
