### ISSUE TITLE
sending on rename not working

### ISSUE THREAD

**Issue by Iguana9999phil** [Cloudbox/autoscan#37]
Error when renaming a file via Radarr.

2:35PM TRC Received JSON body event={"eventType":"Rename","isUpgrade":false,"movie":{"FolderPath":"/home/plex/media/Movies4K/Asterix The Secret of the Magic Potion (2018)"},"movieFile":{"RelativePath":""}} method=POST request_id=bt5kh5qn153b54c7101g url=/triggers/4k
2:35PM ERR Required fields are missing method=POST request_id=bt5kh5qn153b54c7101g url=/triggers/4k
2:35PM DBG Request processed duration=0.261941 method=POST request_id=bt5kh5qn153b54c7101g status=400 url=/triggers/4k

**Comment by m-rots** [comment]
As noted in the readme, rename events are not supported, see [point 6](https://github.com/Cloudbox/autoscan#connecting-the--arrs):
```
6. Select "On Import" and "On Upgrade"
```

Rename events from Sonarr and Radarr are not supported because they lack information. We only get to know the new path, not the old path. If a folder was renamed, then we cannot tell Plex/Emby to remove the old folder.

As a solution try using the Bernard (Google Drive) trigger for rename support or wait for the upcoming `inotify` trigger which can pick up rename events from the filesystem directly.
