### ISSUE TITLE
Autoscan not emptying trash after scanning?

### ISSUE THREAD

**Issue by Iguana9999phil** [Cloudbox/autoscan#42]
Has the auto empty trash for the scanned section been removed? I'm running autoscan on a test Plex server and I'm seeing a lot of "Unavailable" duplicates or trash icons, my other server running PAS has no issues.

**Comment by m-rots** [comment]
Autoscan, unlike PAS, does not empty the trash in Plex. Instead, it will prevent Plex from making scans while one of your mounts is down. So you can safely turn on the setting for Plex where it empties the trash itself.

**Comment by Iguana9999phil** [comment]
Ok that's clear.
Besides that though what other features are not in autoscan which were in PAS? It seems since running autoscan there are a lot of unmatched media again. Is the check match feature removed as well?

**Comment by m-rots** [comment]
Autoscan indeed doesn’t fix media as well. As a rule of thumb, anything that isn’t mentioned in the readme, isn’t included in Autoscan as well.

The “fix media” has been removed because of:
- database dependency. Autoscan currently works without having to hook up the Plex and Emby database files.
- new Plex developments allowing IMDb / TMDb IDs in the file name.
- new tools such as matcharr being able to fix media as well.

**Comment by dcplaya** [comment]
If autoscan crashes, then there is nothing preventing Plex from auto emptying trash, correct?  Just want to make sure I understand is all
