### ISSUE TITLE
When library file is upgraded, library trash is not emptied

### ISSUE THREAD

**Issue by jbh-cloud** [Cloudbox/autoscan#84]
Hi all, first off thanks for this new rewrite, is super simple and slick!

I've got everything running smoothly so far but have noticed that if a file is upgraded, the old file remains until I manually 'Empty trash' for the associated library.

I can't see anything regarding trash emptying in the config or code, is this to be expected?

**Comment by m-rots** [comment]
Please check existing issues before creating a new one:

- https://github.com/Cloudbox/autoscan/issues/42
- https://github.com/Cloudbox/autoscan/issues/52

TLDR:
Unlike PAS, Autoscan does not manage trash and instead assumes that you have the 'automatically clear trash' setting in Plex enabled.

**Comment by jbh-cloud** [comment]
@m-rots  thanks for the clarification. I didn't think to read closed tickets. May be worth adding something to the README.md

**Comment by 6twenty** [comment]
Sorry to bring up such an old discussion again, but just wanted to point out an annoying side effect here: when Plex is set to automatically empty trash, it seems to do so the moment it detects that a file has been deleted _even if it has been replaced by a new file_. This means that media upgrades cause Plex to see it as a new unwatched item.

IMO, this is a failing on Plex's part for not waiting until the scan is complete (by which time it would have picked up the new file and matched it to the same media) before emptying the trash. However it would also have been nice to be able to configure Autoscan to manage emptying of trash after a scan in order to work around the problem. I understand the reasons why it's not possible to implement such a feature in Autoscan _[shakes fist at Plex]_ but perhaps it's worth revisiting to see if Plex's websockets now expose enough information about scans to be able to pull this off?

**Comment by kirsch33** [comment]
a year later, I support @6twenty comments above
